CollegeManagement/urls.py
from django.contrib import admin
from django.urls import path,include
from main import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

main/urls.py
from django.urls import path
from main import views

urlpatterns=[
    path('',views.Index.as_view()),
    path('college/<int:pk>/',views.CollegeDetail.as_view(),name='college'),
    path('college/',views.CollegeList.as_view()),
    path('create_student/',views.StudentCreate.as_view()),
    path('create_college/',views.CollegeCreate.as_view()),
    path('update_college/<int:pk>',views.CollegeUpdate.as_view()),
    path('update_student/<int:pk>',views.StudentUpdate.as_view()),
    path('delete_college/<int:pk>',views.CollegeDelete.as_view()),

]

main/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=256)
    roll_number = models.IntegerField(unique=True)
    college = models.ForeignKey('College',on_delete = models.CASCADE)

    def __str__(self):
        return self.name

class College(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name

main/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse

from django.views.generic import (
    DetailView,
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)
from main import models

# Create your views here.
class Index(View):
    def get(self,request):
        return HttpResponse("Get Request")
    def post(self,request):
        return HttpResponse("Post Request")

class CollegeDetail(DetailView):
    model = models.College
    template_name = 'college_detail.html'

class CollegeList(ListView):
    model = models.College
    template_name = 'college_list.html'
    context_object_name = 'colleges'

class StudentCreate(CreateView):
    model = models.Student
    template_name = 'create_student.html'
    fields = '__all__'
    success_url = '/college'

class CollegeCreate(CreateView):
    model = models.College
    template_name = 'create_college.html'
    fields = '__all__'
    success_url = '/college'

class CollegeUpdate(UpdateView):
    model = models.College
    template_name = 'create_college.html'
    fields = '__all__'
    success_url = '/college'

class StudentUpdate(UpdateView):
    model = models.Student
    template_name = 'create_student.html'
    fields = '__all__'
    success_url = '/college'

class CollegeDelete(DeleteView):
    model = models.College
    template_name = 'confirm.html'
    success_url = '/college'

templates/college_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>College</h1>
    Name:{{object.name}}
    <ul>
        {% for student in object.student_set.all %}
        <li>{{student}}</li>
        {%endfor%}
    </ul>
</body>
</html>

templates/college_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Colleges</h1>
    <br>
    <ul>
    {% for college in colleges %}
    <li>
    <a href="{% url 'college' college.pk %}">{{college.name}}</a>
</li>
    {% endfor %}
</ul>
</body>
</html>

templates/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        <label for="">Are you Sure</label>
        <button>No</button>
        <button type="submit">Yes</button>
    </form>
</body>
</html>

templates/create_college.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

templates/create_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit">Submit</button>
    </form>
</body>
</html>